### ISSUE TITLE
swagger authentication annotations missing

### ISSUE THREAD

**Issue by Hevelian** [Hevelian/hevelian-identity-server#1]
The YAML file generated from swagger does not contain any authentication information, so the client api is unusable.

**Comment by yuflyud** [comment]
Fixed in https://github.com/Hevelian/hevelian-identity-server/commit/428f223985660b36dced3dc50b8ac5b40b62cb38. Added info to operations:
`"security":[{"default":["require_auth"]}]}}`
Security definitions:
`"securityDefinitions":{"default":{"type":"basic"}}`
These changes are also reflected on the Swagger UI.
